from django.urls import path
from .views import (home_page, Faculity_list, Faculity_create, Faculity_edit, Faculity_delete,
                    Kafedra_list, Kafedra_create, Kafedra_edit, Kafedra_delete, Subject_list, Subject_create,
                    Subject_edit, Subject_delete, Teacher_list, Teacher_create, Teacher_edit, Teacher_delete,
                    Group_list, Group_create, Group_edit, Group_delete, Student_list, Student_create, Student_edit,
                    Student_delete, )

urlpatterns = [
    path("", home_page, name="home_page"),
    path("Faculity/list", Faculity_list, name="faculity_list"),
    path("Faculity/create", Faculity_create, name="faculity_create"),
    path("Faculity/<int:pk>/edit/", Faculity_edit, name="faculity_edit"),
    path("Faculity/<int:pk>/delete/", Faculity_delete, name="faculity_delete"),
    path("Kafedra/create", Kafedra_create, name="kafedra_create"),
    path("Kafedra/list", Kafedra_list, name="kafedra_list"),
    path("Kafedra/<int:pk>/edit/", Kafedra_edit, name="kafedra_edit"),
    path("Kafedra/<int:pk>/delete/", Kafedra_delete, name="kafedra_delete"),
    path("Subject/list", Subject_list, name="subject_list"),
    path("Subject/create", Subject_create, name="subject_create"),
    path("Subject/<int:pk>/edit/", Subject_edit, name="subject_edit"),
    path("Subject/<int:pk>/delete/", Subject_delete, name="subject_delete"),
    path("Teacher/list", Teacher_list, name="teacher_list"),
    path("Teacher/create", Teacher_create, name="teacher_create"),
    path("Teacher/<int:pk>/edit/", Teacher_edit, name="teacher_edit"),
    path("Teacher/<int:pk>/delete/", Teacher_delete, name="teacher_delete"),
    path("Group/list", Group_list, name="group_list"),
    path("Group/create", Group_create, name="group_create"),
    path("Group/<int:pk>/edit/", Group_edit, name="group_edit"),
    path("Group/<int:pk>/delete/", Group_delete, name="group_delete"),
    path("Student/list", Student_list, name="student_list"),
    path("Student/create", Student_create, name="student_create"),
    path("Student/<int:pk>/edit/", Student_edit, name="student_edit"),
    path("Student/<int:pk>/delete/", Student_delete, name="student_delete"),
]
